name: Compile native app on Linux
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install dependencies
        run: 'sudo apt-get update && sudo apt-get -y install build-essential libreadline-dev libboost-all-dev libsdl2-image-dev libsdl2-dev'
      - name: Build
        run: "echo 'CFLAGS_NATIVE = -Werror -O0 -DENABLE_DEBUGGER $(shell sdl2-config --cflags)' > src/Makefile.local && make -j2 bin"
    
