name: Build and deploy release (PWA, CP embedded)
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
env:
  EM_VERSION: 3.1.64
  NODE_VERSION: 22
  EM_CACHE_FOLDER: emsdk-cache
  PAGES_REPO_URL: git@github.com:cloudpilot-emu/cloudpilot-emu.github.io.git
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TAG: ${GITHUB_REF##*/}
  CP_EMBEDDED_ZIP_CONTENT: npm-embedded/dist/*
  CP_EMBEDDED_ZIP_NAME: cloudpilot-emu-embedded-${GITHUB_REF##*/}.zip
jobs:
  wait-for-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Wait for relase to be created
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: Create release
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
  build_and_release:
    runs-on: ubuntu-20.04
    needs: wait-for-release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Get version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Validate package.json version
        run: echo 'if (require("./web/package.json").version !== "${{steps.version.outputs.VERSION}}") process.exit(1)' | node
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v3
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}-2
      - name: Setup emscripten
        uses: DirtyHairy/setup-emsdk@master
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: Build wasm
        run: make -Csrc -j2 emscripten
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Install node deps
        working-directory: web
        run: yarn install
      - name: Lint
        working-directory: web
        run: yarn lint
      - name: Test
        working-directory: web
        run: yarn test
      - name: Build CloudpilotEmu embedded
        working-directory: web
        run: CP_RELEASE=1 yarn dist-embedded
      - name: Build PWA
        working-directory: web
        run: |
          yarn run gen-revision
          yarn build --base-href /app/
          yarn generate-worker
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.1
        with:
            ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Checkout pages source
        run: git clone --depth 1 ${{env.PAGES_REPO_URL}}
      - name: Copy and deploy
        working-directory: cloudpilot-emu.github.io
        run: |
          test -x app-preview && rm -fr app
          test -x embedded && rm -fr embedded
          cp -r ../web/build-pwa ./app
          cp -r ../web/dist-embedded ./embedded
          git add .
          git config --global user.email "golem@nowhere.org"
          git config --global user.name "The Golem"
          git commit -m "Bump."
          git push
      - name: Upload CP embedded release files
        working-directory: web
        run: |
          zip -j ${{ env.CP_EMBEDDED_ZIP_NAME }} ${{ env.CP_EMBEDDED_ZIP_CONTENT }}
          gh release upload ${{ env.TAG }} ${{ env.CP_EMBEDDED_ZIP_NAME }}
      - name: Publish CP embedded to NPM
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          package: web/npm-embedded

